name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies backend
        working-directory: ./backend
        run: npm install  

      - name: Install dependencies tests
        working-directory: ./tests
        run: npm install

      - name: Make Jest executable
        run: chmod +x ./tests/node_modules/.bin/jest

      - name: Run tests
        working-directory: ./tests
        run: npm test
